# Generated by Django 4.0.1 on 2022-01-16 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_item2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item2',
        ),
    ]
