# Generated by Django 4.0.1 on 2022-01-23 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item2',
            options={'verbose_name': 'Item2', 'verbose_name_plural': 'Items2'},
        ),
    ]
